name: containerize
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: chenghuilee/imsearch
          # tags: |
          #   # minimal (short sha)
          #   type=sha,prefix=sha-
          #   # type=ref,event=branch
          flavor: |
            latest=auto
            # prefix=latest-,onlatest=true
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-build
          install: true
      
      # - name: Cache Docker layers
      #   uses: actions/cache@v3.0.11
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-multi-buildx
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      
      # - name: Replace cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
